services:
  frontend:
    container_name: transcendence_frontend

    build:
      context: .
      dockerfile: frontend/Dockerfile

    ports:
      - "3000"

    networks:
      transcendence_network:


  nginx:
    container_name: transcendence_nginx

    build:
      context: .
      dockerfile: services/nginx/Dockerfile

    ports:
      - "8443:443"

    networks:
      transcendence_network:

  api:
    container_name: transcendence_api

    build:
      context: .
      dockerfile: services/api/Dockerfile

    env_file:
        - env/prod/.env.api
    environment:
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    ports:
      - "3000"

    networks:
      transcendence_network:

  user:
    container_name: transcendence_user

    build:
      context: .
      dockerfile: services/user/Dockerfile

    env_file:
        - env/prod/.env.user
    ports:
      - "3001"

    networks:
      transcendence_network:

  auth:
    container_name: transcendence_auth

    build:
      context: .
      dockerfile: services/auth/Dockerfile

    env_file:
        - env/prod/.env.auth
    environment:
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    ports:
      - "3002"

    networks:
      transcendence_network:

  stats:
    container_name: transcendence_stats

    build:
      context: .
      dockerfile: services/game_stats/Dockerfile

    env_file:
        - env/prod/.env.game_stats
    ports:
      - "3003"

    networks:
      transcendence_network:

networks:
  transcendence_network:
    driver: bridge
