services:
  frontend:
    container_name: transcendence_frontend

    build:
      context: .
      dockerfile: frontend/Dockerfile

    ports:
      - "8080:80"

    networks:
      transcendence_network:

  api:
    container_name: transcendence_api

    build:
      context: .
      dockerfile: backend/api/Dockerfile

    ports:
      - "3001:3000"

    networks:
      transcendence_network:

networks:
  transcendence_network:
    driver: bridge
